/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.lawrence.random.randomservice;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-05-09")
public class InvalidRandomRange extends org.apache.thrift.TException
        implements org.apache.thrift.TBase<InvalidRandomRange, InvalidRandomRange._Fields>, java.io.Serializable,
        Cloneable, Comparable<InvalidRandomRange> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct(
            "InvalidRandomRange");

    private static final org.apache.thrift.protocol.TField DESC_FIELD_DESC = new org.apache.thrift.protocol.TField(
            "desc", org.apache.thrift.protocol.TType.STRING, (short) 1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY =
            new InvalidRandomRangeStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY =
            new InvalidRandomRangeTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable String desc; // optional

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        DESC((short) 1, "desc");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // DESC
                    return DESC;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final _Fields optionals[] = { _Fields.DESC };
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields,
                org.apache.thrift.meta_data.FieldMetaData>(
                _Fields.class);
        tmpMap.put(_Fields.DESC,
                new org.apache.thrift.meta_data.FieldMetaData("desc", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(InvalidRandomRange.class, metaDataMap);
    }

    public InvalidRandomRange() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public InvalidRandomRange(InvalidRandomRange other) {
        if (other.isSetDesc()) {
            this.desc = other.desc;
        }
    }

    @Override
    public InvalidRandomRange deepCopy() {
        return new InvalidRandomRange(this);
    }

    @Override
    public void clear() {
        this.desc = null;
    }

    @org.apache.thrift.annotation.Nullable
    public String getDesc() {
        return this.desc;
    }

    public InvalidRandomRange setDesc(@org.apache.thrift.annotation.Nullable String desc) {
        this.desc = desc;
        return this;
    }

    public void unsetDesc() {
        this.desc = null;
    }

    /** Returns true if field desc is set (has been assigned a value) and false otherwise */
    public boolean isSetDesc() {
        return this.desc != null;
    }

    public void setDescIsSet(boolean value) {
        if (!value) {
            this.desc = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
        switch (field) {
            case DESC:
                if (value == null) {
                    unsetDesc();
                } else {
                    setDesc((String) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field) {
        switch (field) {
            case DESC:
                return getDesc();

        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case DESC:
                return isSetDesc();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that instanceof InvalidRandomRange) {
        return this.equals((InvalidRandomRange) that);
      }
        return false;
    }

    public boolean equals(InvalidRandomRange that) {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_desc = true && this.isSetDesc();
        boolean that_present_desc = true && that.isSetDesc();
        if (this_present_desc || that_present_desc) {
          if (!(this_present_desc && that_present_desc)) {
            return false;
          }
          if (!this.desc.equals(that.desc)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetDesc()) ? 131071 : 524287);
      if (isSetDesc()) {
        hashCode = hashCode * 8191 + desc.hashCode();
      }

        return hashCode;
    }

    @Override
    public int compareTo(InvalidRandomRange other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetDesc(), other.isSetDesc());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetDesc()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.desc, other.desc);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InvalidRandomRange(");
        boolean first = true;

        if (isSetDesc()) {
            sb.append("desc:");
            if (this.desc == null) {
                sb.append("null");
            } else {
                sb.append(this.desc);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(
                    new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(
                    new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class InvalidRandomRangeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public InvalidRandomRangeStandardScheme getScheme() {
            return new InvalidRandomRangeStandardScheme();
        }
    }

    private static class InvalidRandomRangeStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<InvalidRandomRange> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, InvalidRandomRange struct)
                throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // DESC
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.desc = iprot.readString();
                            struct.setDescIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, InvalidRandomRange struct)
                throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.desc != null) {
                if (struct.isSetDesc()) {
                    oprot.writeFieldBegin(DESC_FIELD_DESC);
                    oprot.writeString(struct.desc);
                    oprot.writeFieldEnd();
                }
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class InvalidRandomRangeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public InvalidRandomRangeTupleScheme getScheme() {
            return new InvalidRandomRangeTupleScheme();
        }
    }

    private static class InvalidRandomRangeTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<InvalidRandomRange> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, InvalidRandomRange struct)
                throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetDesc()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetDesc()) {
                oprot.writeString(struct.desc);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, InvalidRandomRange struct)
                throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                struct.desc = iprot.readString();
                struct.setDescIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(
                proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

