/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.randomservice;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-05-09")
public class RandomNumberStruct implements org.apache.thrift.TBase<RandomNumberStruct, RandomNumberStruct._Fields>, java.io.Serializable, Cloneable, Comparable<RandomNumberStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RandomNumberStruct");

  private static final org.apache.thrift.protocol.TField RANDOM_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("randomNumber", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CREATED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("createdAt", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RandomNumberStructStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RandomNumberStructTupleSchemeFactory();

  public int randomNumber; // optional
  public long createdAt; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RANDOM_NUMBER((short)1, "randomNumber"),
    CREATED_AT((short)2, "createdAt");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RANDOM_NUMBER
          return RANDOM_NUMBER;
        case 2: // CREATED_AT
          return CREATED_AT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RANDOMNUMBER_ISSET_ID = 0;
  private static final int __CREATEDAT_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.RANDOM_NUMBER,_Fields.CREATED_AT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RANDOM_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("randomNumber", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATED_AT, new org.apache.thrift.meta_data.FieldMetaData("createdAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RandomNumberStruct.class, metaDataMap);
  }

  public RandomNumberStruct() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RandomNumberStruct(RandomNumberStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.randomNumber = other.randomNumber;
    this.createdAt = other.createdAt;
  }

  @Override
  public RandomNumberStruct deepCopy() {
    return new RandomNumberStruct(this);
  }

  @Override
  public void clear() {
    setRandomNumberIsSet(false);
    this.randomNumber = 0;
    setCreatedAtIsSet(false);
    this.createdAt = 0;
  }

  public int getRandomNumber() {
    return this.randomNumber;
  }

  public RandomNumberStruct setRandomNumber(int randomNumber) {
    this.randomNumber = randomNumber;
    setRandomNumberIsSet(true);
    return this;
  }

  public void unsetRandomNumber() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RANDOMNUMBER_ISSET_ID);
  }

  /** Returns true if field randomNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetRandomNumber() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RANDOMNUMBER_ISSET_ID);
  }

  public void setRandomNumberIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RANDOMNUMBER_ISSET_ID, value);
  }

  public long getCreatedAt() {
    return this.createdAt;
  }

  public RandomNumberStruct setCreatedAt(long createdAt) {
    this.createdAt = createdAt;
    setCreatedAtIsSet(true);
    return this;
  }

  public void unsetCreatedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  /** Returns true if field createdAt is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEDAT_ISSET_ID);
  }

  public void setCreatedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEDAT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RANDOM_NUMBER:
      if (value == null) {
        unsetRandomNumber();
      } else {
        setRandomNumber((java.lang.Integer)value);
      }
      break;

    case CREATED_AT:
      if (value == null) {
        unsetCreatedAt();
      } else {
        setCreatedAt((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RANDOM_NUMBER:
      return getRandomNumber();

    case CREATED_AT:
      return getCreatedAt();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RANDOM_NUMBER:
      return isSetRandomNumber();
    case CREATED_AT:
      return isSetCreatedAt();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RandomNumberStruct)
      return this.equals((RandomNumberStruct)that);
    return false;
  }

  public boolean equals(RandomNumberStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_randomNumber = true && this.isSetRandomNumber();
    boolean that_present_randomNumber = true && that.isSetRandomNumber();
    if (this_present_randomNumber || that_present_randomNumber) {
      if (!(this_present_randomNumber && that_present_randomNumber))
        return false;
      if (this.randomNumber != that.randomNumber)
        return false;
    }

    boolean this_present_createdAt = true && this.isSetCreatedAt();
    boolean that_present_createdAt = true && that.isSetCreatedAt();
    if (this_present_createdAt || that_present_createdAt) {
      if (!(this_present_createdAt && that_present_createdAt))
        return false;
      if (this.createdAt != that.createdAt)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetRandomNumber()) ? 131071 : 524287);
    if (isSetRandomNumber())
      hashCode = hashCode * 8191 + randomNumber;

    hashCode = hashCode * 8191 + ((isSetCreatedAt()) ? 131071 : 524287);
    if (isSetCreatedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createdAt);

    return hashCode;
  }

  @Override
  public int compareTo(RandomNumberStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetRandomNumber(), other.isSetRandomNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRandomNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.randomNumber, other.randomNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreatedAt(), other.isSetCreatedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdAt, other.createdAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RandomNumberStruct(");
    boolean first = true;

    if (isSetRandomNumber()) {
      sb.append("randomNumber:");
      sb.append(this.randomNumber);
      first = false;
    }
    if (isSetCreatedAt()) {
      if (!first) sb.append(", ");
      sb.append("createdAt:");
      sb.append(this.createdAt);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RandomNumberStructStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RandomNumberStructStandardScheme getScheme() {
      return new RandomNumberStructStandardScheme();
    }
  }

  private static class RandomNumberStructStandardScheme extends org.apache.thrift.scheme.StandardScheme<RandomNumberStruct> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RandomNumberStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RANDOM_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.randomNumber = iprot.readI32();
              struct.setRandomNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CREATED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createdAt = iprot.readI64();
              struct.setCreatedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RandomNumberStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetRandomNumber()) {
        oprot.writeFieldBegin(RANDOM_NUMBER_FIELD_DESC);
        oprot.writeI32(struct.randomNumber);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeFieldBegin(CREATED_AT_FIELD_DESC);
        oprot.writeI64(struct.createdAt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RandomNumberStructTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RandomNumberStructTupleScheme getScheme() {
      return new RandomNumberStructTupleScheme();
    }
  }

  private static class RandomNumberStructTupleScheme extends org.apache.thrift.scheme.TupleScheme<RandomNumberStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RandomNumberStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRandomNumber()) {
        optionals.set(0);
      }
      if (struct.isSetCreatedAt()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRandomNumber()) {
        oprot.writeI32(struct.randomNumber);
      }
      if (struct.isSetCreatedAt()) {
        oprot.writeI64(struct.createdAt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RandomNumberStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.randomNumber = iprot.readI32();
        struct.setRandomNumberIsSet(true);
      }
      if (incoming.get(1)) {
        struct.createdAt = iprot.readI64();
        struct.setCreatedAtIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

