apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-service
  name: cassandra-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30942
  selector:
    app: cassandra
